services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=online_judge'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

